# only use with supported cloud platforms! Or set proxy server by yourself (Nginx, etc)
apiVersion: v1
kind: Service
metadata:
 name: nginx-load-balancer
spec:
 type: LoadBalancer
 selector:
   run: app-nginx
 ports:

 - port: 80
   targetPort: 80