apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  namespace: dev # will be autoset to default BS if not set
spec:
  type: ClusterIP
  selector:
   app: app-nginx
   type: backend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP