apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-certificate
  # namespace: nginx1
spec:
  secretName: nginx1
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - 'k8s.devcraft.app'