apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    # Configure your email here...
    # ---
    email: slayoffer@gmail.com

    # Configure your server here...
    # ---
    # Letsencrypt Production
    server: https://acme-v02.api.letsencrypt.org/directory
    # - or -
    # Letsencrypt Staging
    # server: https://acme-staging-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    # DNS Challenge:
    - dns01:
        # Configure your DNS Provider here...
        # ---
        cloudflare:
          email: slayoffer@gmail.com
        # API Key:
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
        # - or -
        # API Token:
        #   apiTokenSecretRef:
        #     name: cloudflare-api-token-secret
        #     key: api-token        
      # (Optional) Add DNS selectors
      # ---
      # selector:
      #   dnsZones:
      #   - 'your-domain'

    # HTTP Challenge:
    # - http01:
    #    ingress:
    #      class: traefik