apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    app: myapp
    type: front-end
  annotations: # extra info for people, not for k8s
    buildversion: "1.34"
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
        type: some-type
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      app: myapp
      type: some-type
  replicas: 3
